import styles from '../styles/Layout.module.css';
import Head from 'next/head';
import Navbar from '../components/Navbar/Navbar';
import Hero from '../components/Hero';
import About from '../components/About';
import Specials from '../components/Specials/Specials';
import Menu from '../components/Menu/Menu';
import Book from '../components/Book';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <>
        <Head>
        <title>Fiasco Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="Food, Recipes, Restaurant" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <script src="https://use.fontawesome.com/0b056472e2.js"></script>
      </Head>
        <div className={styles.mainContainer}>
            <div className={styles.container}>
                <header className={styles.header}>
                    <Navbar/>
                    <Hero/>
                </header>

                <main className={styles.main}>
                    <About/>
                    <Specials/>
                    <Menu/>
                    <Book/>
                </main>

                <footer className={styles.footer}>
                    <Footer/>
                </footer>
            </div>
        </div>
        </>
  )
}
